### ISSUE TITLE
The playtrack documentation appears to be incorrect.

### ISSUE THREAD

**Issue by mqnowa** [Aran404/SpotAPI#5]
https://github.com/Aran404/SpotAPI/blob/main/docs/player.md

Although the documentation states that the URI should be specified, it is actually the trailing ID.

❌
```python
player.play_track("spotify:track:6rqhFgbbKwnb9MLmUQDhG6", "spotify:playlist:37i9dQZF1DXcBWIGoYBM5M")
```

⭕
```python
player.play_track("6rqhFgbbKwnb9MLmUQDhG6", "37i9dQZF1DXcBWIGoYBM5M")
```

**Comment by Aran404** [comment]
It parses both respectively.
