### ISSUE TITLE
Add JSON Extraction Functionality for Tracks, Albums, and Playlists

### ISSUE THREAD

**Issue by afkarxyz** [Aran404/SpotAPI#8]
Hi, could you add functionality to extract JSON files for tracks, albums, and playlists?

**Comment by Aran404** [comment]
Could you elaborate please?

**Comment by afkarxyz** [comment]
![image](https://github.com/user-attachments/assets/bedc0b08-e4fa-4656-9690-ff6cc60d260c)

"I've tested it for playlists, and it works, but for albums and tracks, it seems like they are not mentioned in the README.

I tested using the following methods:

```python
import json
from spotapi import PublicAlbum

def get_album_raw_json(album_url):
    album = PublicAlbum(album_url)
    return album.get_album_info()

album_url = "https://open.spotify.com/album/2noRn2Aes5aoNVsU6iv3c0"
raw_json = get_album_raw_json(album_url)
print(json.dumps(raw_json, indent=2))
```

or

```python
import json
from spotapi import PublicTrack

def get_track_raw_json(track_url):
    track = PublicTrack(track_url)
    return track.get_track_info()

track_url = "https://open.spotify.com/track/0WbMK4wrZ1wFSty9F7FCgu"
raw_json = get_track_raw_json(track_url)
print(json.dumps(raw_json, indent=2))
```

but I encountered an error."

- ImportError: cannot import name 'PublicAlbum' from 'spotapi'
- ImportError: cannot import name 'PublicTrack' from 'spotapi'

**Comment by Aran404** [comment]
I'll put this in my todo. Thanks.

**Comment by afkarxyz** [comment]
Thanks! Looking forward to the updates.

**Comment by Aran404** [comment]
I've added the suggestions, have a look at let me know if any issues arises. Thanks again.

**Comment by afkarxyz** [comment]
I checked in branches and pypi.org there is no update, where did you add it?

**Comment by Aran404** [comment]
Seems I somehow didn't push it, will do that tomorrow. I think it has something to do with the new MFA mandate

**Comment by Aran404** [comment]
Should be good now.

**Comment by afkarxyz** [comment]
Thank you so much for the update; everything is working like a charm now. 👍
