### ISSUE TITLE
Episode (podcast) info

### ISSUE THREAD

**Issue by noembryo** [Aran404/SpotAPI#9]
This is more of a question (or a feature request).
Is it possible to get info from an episode link like `https://open.spotify.com/episode/5CZlLoGOibAGX9oLh26YEk`?

Anyway, thank you for your library and your time.
It's been a life saver.. 👍

**Comment by Aran404** [comment]
The current API does not support it. I'll add this feature request to my TODO. Thanks.

**Comment by noembryo** [comment]
Thank you..

**Comment by Aran404** [comment]
Do you think it would be more suitable to make a "PublicInfo" class that has all the paginators that don't require authentication? Or just keep it in it's respectable file?

**Comment by noembryo** [comment]
Yes, I think one class could be really handy.. 💯

**Comment by Aran404** [comment]
I thought that as well, I'll just point to the function in the original class to have backwards compatibility.

**Comment by noembryo** [comment]
Great! Waiting for the update.. 😃

**Comment by Aran404** [comment]
I've added the suggestions you requested, please test and let me know if there any issues.

**Comment by noembryo** [comment]
Nice.. It is almost a drop-in replacement, but has a few differences.
- Importing `PublicPlaylist` from `public` and doing `info = play_list.get_playlist_info(limit=343)["data"]["playlistV2"]` produces an error, but if I import from `spotapi.playlist` it works.
To fix it I have to do
```
    info = play_list.get_playlist_info(limit=343)
    info = info["data"]["playlistV2"]
```
- Importing `PublicAlbum` from `public` and doing `info = album.get_album_info(limit=343)["data"]["albumUnion"]` produces an error, but if I import from `spotapi.album` it works.
To fix it I have to do `info = album.get_album_info()["data"]["albumUnion"]`

Trying to get the playlist info using `info = list(Public().playlist_info(url))[0]` works fine and I can get all the items with `items = [item for sublist in info for item in sublist["items"]]`, but unfortunately `info` does not include the playlist's title that I previously got with `info["name"]`  
The same applies to the albums. Getting the items with `info = Public().album_info(url)` returns a generator for the album items, but there is no way to get the album's title that I use to get with `alb_title = info["name"]`.

For the podcast part now.
I had no success with the [test link I use](https://open.spotify.com/episode/5CZlLoGOibAGX9oLh26YEk).
- If I use the `info = Public().podcast_episode_info(url)`, I get a generator with this `{'data': {'episodeUnionV2': {'__typename': 'GenericError'}}, 'extensions': {}}` in it.
- If I use this
```
        info = Public().podcast_info(url)
        for i in info:
            print(i)
```
    I get an `IndexError: list index out of range`

These are my first observations. I'll keep investigating.. 🤓 
🙏

**Comment by Aran404** [comment]
Well, Public provides the paginators of the objects which has stayed the same from Version 1.1.1 and Version 1.1.2. I think you are confusing pagination (which parses the information somewhat) and getting the raw data. Also Public is a class full of static methods so what you'd do is Public.(methodhere).

**Comment by Aran404** [comment]
Well, Public provides the paginators of the objects which has stayed the same from Version 1.1.1 and Version 1.1.2. I think you are confusing pagination (which parses the information somewhat) and getting the raw data. Also Public is a class full of static methods so what you'd do is Public.(methodhere).

**Comment by noembryo** [comment]
Well, my bad. Although `Public.podcast_episode_info(url)` uses the class' static method and `Public().podcast_episode_info(url)`  uses one instance's static method, the outcome is the same generator with the same error.
And since I'm using the library in a somewhat wrong way, can you please tell me what is the intended way to get the data for a playlist, an album or a podcast?

Thank you for your help..

**Comment by Aran404** [comment]
To get the raw data, just use it the normal way by importing the specific class you want to use. Public just acts as an atlas to the underlying methods.

**Comment by noembryo** [comment]
A, OK.
Did you see the podcast's error?

**Comment by Aran404** [comment]
Yes I did, Issue #10 mentions it, will work up a fix when I'm home.

**Comment by noembryo** [comment]
Oh, thank you. I'll monitor it there.. 🙏

**Comment by noembryo** [comment]
> Yes I did, Issue #10 mentions it, will work up a fix when I'm home.

Is the fix that you mention there published?
Because I can't see an update..

**Comment by Aran404** [comment]
Yeah it is.

**Comment by noembryo** [comment]
> Yeah it is.

Well, the most recent release I see, is the 1.1.2, but this is the one I got more than a couple of days ago.
Looking at the dates though, it seems that this 1.1.2 was released yesterday.
Should I remove and re-install the same version?

**Comment by afkarxyz** [comment]
> > Yeah it is.
> 
> Well, the most recent release I see, is the 1.1.2, but this is the one I got more than a couple of days ago. Looking at the dates though, it seems that this 1.1.2 was released yesterday. Should I remove and re-install the same version?

I think he hasn't bumped to version 1.1.3, I downloaded the repository manually without going through pip.

**Comment by noembryo** [comment]
Thank you. 🙏 
I'll try with the re-install..

**Comment by noembryo** [comment]
Nope, still the same error.
Tried uninstalling and re-installing from PyPi
Tried uninstalling and installing from GitHub

I must be doing something wrong.
How can I get the raw data for an episode like this `https://open.spotify.com/episode/5CZlLoGOibAGX9oLh26YEk`?

**Comment by afkarxyz** [comment]
> Nope, still the same error. Tried uninstalling and re-installing from PyPi Tried uninstalling and installing from GitHub
> 
> I must be doing something wrong. How can I get the raw data for an episode like this `https://open.spotify.com/episode/5CZlLoGOibAGX9oLh26YEk`?

You can try my project here https://github.com/afkarxyz/spotifyapis or go directly here https://spotifyapis.vercel.app/

**Comment by noembryo** [comment]
> You can try my project here https://github.com/afkarxyz/spotifyapis or go directly here https://spotifyapis.vercel.app/

I see that you're using the paginators from `Public`, but I was looking for a way to do it like I get the raw playlist data.
Something like
```
        pod = Podcast(client=client)
        info = pod.get_episode(url)
```
I'll have to read more of your project later, but I was hopping for 2-3 lines of code that get the podcast's data..

**Comment by noembryo** [comment]
@afkarxyz Also trying to get the info for my [testcase](https://open.spotify.com/episode/5CZlLoGOibAGX9oLh26YEk) from  https://spotifyapis.vercel.app/ returns a 404..

**Comment by afkarxyz** [comment]
> @afkarxyz Also trying to get the info for my [testcase](https://open.spotify.com/episode/5CZlLoGOibAGX9oLh26YEk) from https://spotifyapis.vercel.app/ returns a 404..

Try this https://spotifyapis.vercel.app/episode/5CZlLoGOibAGX9oLh26YEk

**Comment by noembryo** [comment]
So, how can I get this too?

**Comment by Aran404** [comment]
Sorry about that, 1.1.3 is out now on PyPi.
